### ISSUE TITLE
Installed correctly but not working...

### ISSUE THREAD

**Issue by jamiolee** [johndoh/roundcube-contextmenu#127] opened 2021-01-22 21:59 UTC
I have installed this plugin and I cannot get the menu to display. I have tested this in Firefox, Chrome and Edge on Win10 machine.

Running:
CentOS 7 (CLOUDLINUX 7.8 kvm [server] )
cPanel & WHM Version 92.0.9
Roundcube Webmail 1.4.10
Context Menu 3.2.1

I have created a folder at: home/usr/local/cpanel/base/3rdparty/roundcube/plugins/contextmenu (permissions 0755).
Within that I have extracted the files for roundcube-contextmenu 3.2.1 (permissions 644 for files, and 0755 for folders "localization" and "skins").

Then I edited home/usr/local/cpanel/base/3rdparty/roundcube/config/config.inc.php
to add contextmenu to $config['plugins'].

When I right click on any email in the inbox nothing appears - literally nothing. If I remove the "contextmenu" from the $config['plugins'], then refresh the Roundcube page and right click I get the usual browser right-click menu. I then re-add the "contextmenu" to the config file and refresh and then no right click menu at all.

I have opened the console in both Firefox and Chrome and see no error messages after refreshing the page and trying to right-click again. I have tried troubleshooting on Google and can't find anyone else that has experienced this exact same issue. I am assuming it will have something to do with jQuery but I don't know how to debug this.

Any help would be greatly appreciated, thanks!

Edit: I should add that I can right-click in the inbox area while not hovering over an email message and I will see the usual browser right-click menu, however right-clicking on an email item shows nothing at all. I can take a video recording of this if that would help at all?

Edit 2: I ran the code below in both Firefox and Chrome console which confirmed that jQuery is running, so I am stumped as to why this is not working for me.

```
window.onload = function() {
   if (window.jQuery) {  
       // jQuery is loaded  
       alert("Yeah!");
   } else {
    alert("Nope!");
   }
}
```

**Comment by johndoh** [comment] 2021-01-23 06:31
If jquery was missing there would be errors in the browser console for sure, it is a core requirement of roundcube.. It sounds like there is an issue in the code which determines the visibility of the individual menu items. what roundcube skin are you using? also have you tried with all other roundcube plugins disabled?

**Comment by jamiolee** [comment] 2021-01-27 18:43
Thanks for the response. I tried disabling all other plugins and that didn't work. I was using the Elastic theme by Aleksander Machniak, so I tried changing it back to the Larry theme and that got the Context Menu plugin working. Ideally, I would like to use the Elastic theme as it's much nicer looking. I see that this plugin does support the theme. Do you have any suggestions on how I can further debug this?

![Roundcube Webmail Preferences](https://user-images.githubusercontent.com/63683310/106037856-0fb2dc00-608c-11eb-9baa-dc1a1c9e921b.jpg)

**Comment by johndoh** [comment] 2021-01-27 21:22
For sure it works fine with Elastic. I guess check the network tab in your browser console and make sure all the resources are loaded correctly.

Starting around like 606 in contextmenu.js is where it loops through all the available menu items and adds them to the context menu.

**Comment by jamiolee** [comment] 2021-02-11 22:20
I have loaded up the Network tab on the console and can see contextmenu.js is loaded. I'm not savvy enough to understand what you mean by the line 606 within the code for loading the menu items. Is there a way for me to troubleshoot this any further?

Here is a screenshot from the Console - Network tab.

![Inspector-Network](https://user-images.githubusercontent.com/63683310/107705641-e68d7080-6c73-11eb-8149-55e42097d327.jpg)

**Comment by johndoh** [comment] 2021-02-12 05:29
There is something strange here. You said you are running version 3.2.1 of the plugin but the file sizes shown in your latest screenshot do not match up with those in that version. Specifically the contextmenu.min.css, in your screenshot it says 1.98KB but the size of the file shipped in 3.2.1 is 1.33KB, see https://github.com/johndoh/roundcube-contextmenu/blob/3.2.1/skins/elastic/contextmenu.min.css. I confirmed in my browser's network tab the file sizes shown match those shown on the GItHub website. I am assuming you have not customised the CSS so you would appear to have a broken install. 

A file size of 1.98KB matches that of the file currently available in git-master which is not the same thing as version 3.2.1 so please make sure you have the correct version of the plugin installed.

**Comment by jamiolee** [comment] 2021-02-12 19:47
Thank you for pointing that out, you're right I was using the version. I went ahead and updated it on the server to v.3.2.1 - unfortunately that did not solve this problem. I ran the same tests previously through Firefox, Chrome and Edge, and even removed it from the plugins config and added it back again to confirm that it is unloading and loading it in Roundcube. 

Here's a screenshot from the About window in Roundcube with version numbers, not sure if there's something that might help there?

![jl-round-ver](https://user-images.githubusercontent.com/63683310/107815238-f4043280-6d27-11eb-9160-7a66506b0f1e.jpg)

**Comment by johndoh** [comment] 2021-02-13 06:42
Since you said you cannot provide any debug information from the code I'm out of ideas. I cannot recreate the issue. I'll leave this ticket open for a little while in case any one else has the same issue and can provide more information.

**Comment by yolorkit** [comment] 2021-09-06 13:11
Ubuntu 18.04.5 LTS x64
Hi, i am using roundcube 1.5-rc and neither contextmenu 3.2.1 nor master work.
rc 1.4.10 works fine with cm 3.2.1 though.
There're no errors in roundcube logs.
When i simply switched from rc 1.4.10 to rc 1.5-rc context menu worked on one of the client machines. However when i removed cookies it stopped working in rc 1.5 but still worked fine in 1.4

**Comment by johndoh** [comment] 2021-09-09 06:33
looks like some kind of server config issue to me, don't block the JS files!

**Comment by johndoh** [comment] 2021-09-09 18:34
I'm going to close this ticket because I don't know what else to do with it, there is no specific information relating to plugin code here.

**Closed by johndoh** 2021-09-09 18:34 UTC

**Comment by kochs-online** [comment] 2023-01-28 19:55
@yolorkit: You probably haven't set the file modes correctly. (Ask me how I guessed… 😁)

If the web server is not allowed to access the plugin files, it will create an error message and serve it with `Content-Type: text/html`. Firefox in turn will not process these [error message] files because the web server also sends HTTP header `X-Content-Type-Options: nosniff` disallowing the browser to try and interprete them as `text/javascript` (cf. MDN Web Docs for details regarding [X-Content-Type-Options](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Content-Type-Options))

In order to fix this you need to grant the web server sufficient access rights to the files and directories.
