### ISSUE TITLE
JS error on this.classes.source

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#98] opened 2017-12-19 09:41 UTC
Maybe caused by me digging around #97, but I saw in the console: TypeError: this.classes.source is undefined in contextmenu.js:776:17.

**Comment by johndoh** [comment] 2017-12-19 15:52
I can't recreate this and this.classes.source is set by default so it looks like it might have been caused by digging. unless there is some regression when a new rcube_context_menu is created

**Comment by alecpl** [comment] 2017-12-19 15:58
I'll test this tomorrow more, but I think the issue might be caused by invalid settings merge. E.g. maybe recursive $.extend() should be used. Classes defined in skins/elastic/functions.js does not include 'source'.

**Comment by johndoh** [comment] 2017-12-29 17:21
The classes defined in skins/elastic/functions.js do not need to include 'source' since Elastic uses the default and $.extend() maintains that. Becuase of the way update_settings() works and the structure of the settings there is no need for recusion, though perhaps it would be a better way of doing it. I've also checked for regression on backwards compatibility and I can't find one so I'm going to close this. If you are still getting the error please reopen with more info.

**Closed by johndoh** 2017-12-29 17:21 UTC
