### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentTarget' of undefined

### ISSUE THREAD

**Issue by stress87** [johndoh/roundcube-contextmenu#106] opened 2018-09-18 10:36 UTC
When I click on a page number in page jumper I get the error
`
Uncaught TypeError: Cannot read property 'currentTarget' of undefined
    at contextmenu.js?s=1429340030:1002
`

**Comment by johndoh** [comment] 2018-09-28 06:10
no feedback. possible dupe of #73

**Closed by johndoh** 2018-09-28 06:10 UTC
